#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server’s active 

echo "server { listen 80; }" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Create a symbolic link to enable the default site
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
