#!/usr/bin/env bash
# 404 error
sudo apt -y update
sudo apt -y install nginx

# Creating index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Permorming a move permanently redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Charles130-Anderson permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Creating the error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var/www/html;\n\t\tinternal;\n\t}"

sudo sed -i "s|listen 80 default_server;|$string_for_replacement|" /etc/nginx/sites-enabled/default

# Test for configuration of syntax errors
sudo nginx -t

# Restaring for changes to reflect
sudo service nginx restart
